#!/bin/sh -ex
# Copyright 2020 Oliver Smith
# SPDX-License-Identifier: GPL-3.0-or-later

# This script runs as soon as the rootfs generated by
# "postmarketos install --ondev" boots up.

# Find the target partition
# ---
# In the future, it should be possible to select the target device and
# partition from the installer. Then it would be possible to install
# postmarketOS from the SD card to the internal storage. There is no QML UI in
# Calamares yet for this, so let's simply install into the "reserved space"
# that "pmbootstrap install --ondev" creates on the same device:
# - p1: boot partition
# - p2: reserved space (target partition)
# - p3: install partition (mounted as /)
part_install="$(df -T / | awk '/^\/dev/ {print $1}')"
part_target="$(echo "$part_install" | sed 's/3$/2/')"

# Sanity check
if [ "$(realpath /dev/disk/by-label/pmOS_install)" != "$part_install" ]; then
	if [ -n "$ONDEV_SKIP_LABEL_CHECK" ]; then
		echo "WARNING: not booting from pmOS_install, but" \
			"ONDEV_SKIP_LABEL_CHECK is set."
	else
		echo "ERROR: ondev-boot should only be started from the" \
			"pmOS_install partition!"
		exit 1
	fi
fi

# Calamares module "unpackfs" needs loop
modprobe loop || true

# Configure lightdm to start i3
mkdir -p /usr/share/lightdm/lightdm.conf.d
cat << EOF > /usr/share/lightdm/lightdm.conf.d/00-autologin.conf
[Seat:*]
autologin-user=root
autologin-user-timeout=0
autologin-session=i3
EOF

# Configure i3 to start calamares
mkdir -p /root/.config/i3
cat << EOF > /root/.config/i3/config
new_window none
workspace_layout tabbed
exec unclutter-xfixes --fork --timeout 1
exec calamares
EOF

# Set environment variables
cat << EOF > /root/.profile
# Used by partitionq in calamares
export ONDEV_PARTITION_TARGET="$part_target"  # used by "partitionq"
export QT_IM_MODULE="qtvirtualkeyboard"
export QT_VIRTUALKEYBOARD_STYLE=Plasma
EOF

# Hardcode 200 DPI (postmarketos-ondev#15: better would be correct device dpi)
cat << EOF > /root/.Xresources
Xft.dpi: 200
EOF

# DEBUG: add user for ssh (password: 'y')
# yes | adduser user -G wheel || true

rc-service lightdm start
