#!/bin/sh -ex
# Copyright 2020 Oliver Smith
# SPDX-License-Identifier: GPL-3.0-or-later

# This script runs as soon as the rootfs generated by
# "postmarketos install --ondev" boots up.

# Find the target partition
# ---
# In the future, it should be possible to select the target device and
# partition from the installer. Then it would be possible to install
# postmarketOS from the SD card to the internal storage. There is no QML UI in
# Calamares yet for this, so let's simply install into the "reserved space"
# that "pmbootstrap install --ondev" creates on the same device:
# - p1: boot partition
# - p2: reserved space (target partition)
# - p3: install partition (mounted as /)
part_install="$(df -T / | awk '/^\/dev/ {print $1}')"
part_target="$(echo "$part_install" | sed 's/3$/2/')"

# Sanity check
if [ "$(realpath /dev/disk/by-label/pmOS_install)" != "$part_install" ]; then
	echo "ERROR: ondev-boot should only be started from the pmOS_install partition!"
	exit 1
fi

# HACK: avoid crashing without chcon
# https://github.com/calamares/calamares/blob/5e79176f47833fbf44b7f4a2499ad8807ea39284/src/modules/mount/main.py#L52-L56
if ! [ -e /bin/chcon ]; then
	ln -s /bin/true /bin/chcon
fi

# Calamares module "unpackfs" needs loop
modprobe loop

# Configure lightdm to start i3
mkdir -p /usr/share/lightdm/lightdm.conf.d
cat << EOF > /usr/share/lightdm/lightdm.conf.d/00-autologin.conf
[Seat:*]
autologin-user=root
autologin-user-timeout=0
autologin-session=i3
EOF

# Configure i3 to start calamares
mkdir -p /root/.config/i3
cat << EOF > /root/.config/i3/config
new_window 1pixel
workspace_layout tabbed
exec calamares
EOF

# Set ONDEV_PARTITION_TARGET for calamares (used by partitionq)
cat << EOF > /root/.profile
export ONDEV_PARTITION_TARGET="$part_target" 
EOF

# DEBUG: add user for ssh (password: 'y')
# yes | adduser user -G wheel || true

rc-service lightdm start
